### PR TITLE
fix: old upper bound dep for `mean_average_precision`

### PR DESCRIPTION
**Pull request by hadim**
**Checklist:**

- [x] **Commit Message Formatting**: Commit titles and messages follow guidelines in the
  [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/#summary).
- [ ] Documentation has been updated, if necessary.
- [ ] Examples have been added, if necessary.
- [ ] Tests have been added, if necessary.

### CODE REVIEW

**Comment by hadim** [comment]
It prevents `pip check` working correctly, which is problematic for the downstream conda forge package at https://github.com/conda-forge/docling-ibm-models-feedstock

**Comment by hadim** [comment]
ping @dolfim-ibm

**Comment by dolfim-ibm** [comment]
I was just checking. Honestly, I think we should simply remove this dependency, since it is not used.

**Comment by maxmnemonic** [comment]
@hadim thanks for pointing us to this, indeed dependency is not used in the current code, so we will remove it, with this PR: https://github.com/DS4SD/docling-ibm-models/pull/53

**Comment by maxmnemonic** [comment]
@hadim we deleted dependency, closing this PR

**Pull request closed without merging**
